### ISSUE TITLE
BrowserSync 404

### ISSUE THREAD

**Issue by mbalex99** [madhukard/angular2-jspm-seed#1]
Upon changing any files browser sync can't reload the page. I think it's because it's asking for the "localhost:3000/home" when there's only an index.html.

~Btw great job, i'm learning a lot here.

**Comment by madhukard** [comment]
Fixed - https://github.com/madhukard/angular2-jspm-seed/commit/fb59113ff05a67421721b7152a98e83ad8ac968c
