### ISSUE TITLE
Using external javascript library

### ISSUE THREAD

**Issue by friksa** [madhukard/angular2-jspm-seed#3]
BTW, awesome project!!

How do I use an external javascript library?  I have a single .js file that needs to be included.  Where do I place the file and how do I include the file as part of the build process (development and production)?

Thanks!

**Comment by toledosteve** [comment]
@friksa What external javascript library?  Can it be installed via JSPM or NPM?

If you look at **app/index.html** you will see the link

``` javascript
<script src="vendor/angular2-polyfills.min.js"></script>
```

You would include additional tags like above.  Also, if you look at line 33 (development) in **tools/gulp/config.js**, and line 37 in **tools/gulp/config.js** you can specify the paths to any vendor JS files and it will get included in development and production builds.

**Comment by madhukard** [comment]
@friksa check this blog for help - https://blog.nraboy.com/2016/01/include-external-javascript-libraries-in-an-angular-2-typescript-project/?utm_source=javascriptweekly&utm_medium=email

**Comment by friksa** [comment]
Thanks!  I was able to get the external lib working.  Now I am trying to get deployment to work :)  I opened another ticket for that issue.
