### ISSUE TITLE
Production deploy - old way of deployment

### ISSUE THREAD

**Issue by spboyer** [madhukard/angular2-jspm-seed#4]
`gulp deploy` takes the approach of minifying all the scripts into a single `.js` file and does not take advantage of `jspm bundle`, is this just a carry over from a previous project template and targeted for a change or the intent?

**Comment by madhukard** [comment]
gulp deploy uses the jspm class builder api to create single self-executing bundle (single .js file) which internally uses the jspm bundle.

Reference - https://github.com/jspm/jspm-cli/blob/master/docs/api.md
Our Gulp Task - https://github.com/madhukard/angular2-jspm-seed/blob/master/tools/gulp/tasks/production/scripts.js
