### ISSUE TITLE
gulp deploy fails

### ISSUE THREAD

**Issue by friksa** [madhukard/angular2-jspm-seed#5]
```
git clone https://github.com/madhukard/angular2-jspm-seed.git myapp
cd myapp
npm install
jspm install
gulp deploy
```

Fails with 
[17:15:12] 'test-deploy' errored after 2.39 s
[17:15:12] Error: ENFILE: file table overflow, scandir '/angular/myapp/target/production/src'

Even when you comment out the test task, the deployment files fail to load with this error:
app.js:37868 Uncaught ReferenceError: module is not defined

**Comment by madhukard** [comment]
gulp deploy is working fine, check the travis build - https://travis-ci.org/madhukard/angular2-jspm-seed.

I got 'ENFILE: file table overflow' in my build when I updated package.json to use angular2 beta 1 version (npm:angular2@2.0.0-beta.1) as ng2-material still using npm:angular2@2.0.0-beta.0 version.
