### ISSUE TITLE
Console error after install

### ISSUE THREAD

**Issue by ciutadellla** [madhukard/angular2-jspm-seed#7]
TypeError: o.addTask is not a function

at n.(anonymous function) (http://localhost:3000/vendor/angular2-polyfills.min.js:1:14871)

DEPRECATION WARNING: 'enqueueTask' is no longer supported and will be removed in next major release. Use addTask/addRepeatingTask/addMicroTask
angular2-polyfills.min.js:1 

DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask

**Comment by madhukard** [comment]
This belongs to https://github.com/angular/zone.js where the code resides (angular2-polyfills.min.js just bundles zones plus other polyffils).

Reference - 
https://github.com/angular/angular/issues/7007
https://github.com/angular/zone.js/issues/262
