### ISSUE TITLE
karma is failing

### ISSUE THREAD

**Issue by phra** [madhukard/angular2-jspm-seed#8]
hi,

i've just cloned your repo and if i launch 'gulp test' it exits w/:

"Error: EMFILE: too many open files, scandir '/home/phra/experimental/angular2-jspm-seed/target/development/src"

i've not found a working solutions for these unit tests. it's seems a bug of karma or karma-jspm.

can you help me?

**Comment by madhukard** [comment]
Try it after increasing ulimit (ulimit -n 10480). Some times I have got this error on my machine too, it got resolved after rebooting the machine.

**Comment by phra** [comment]
sadly, this is not a solution for a production environment.

**Comment by sonicparke** [comment]
I am having the same issue. I did try to increase ulimit to 10480 but that did not fix the issue.

**Comment by madhukard** [comment]
After updating to Angular2 RC version, I didn't able to reproduce the issue.
